name: nm-wifi-hotspot
base: core20
version: '0.1'
summary: A simple WiFi Hotspot using NetworkManager
description: |
  This snap configures a WiFi hotsport talking to the network-manager snap.
  It is designed to be used on an UbuntuCore appliance image and is only
  tested in that context.

  To use this package you need to have the network-manager snap installed

      snap install network-manager

  ... then connect to the network-manager interface with

      snap connect nm-wifi-hotspot:network-manager network-manager

  This will create a hotspot with the default SSID "UbuntuCore Hotspot" and
  with a WPA2 key set to "0123456789".
  To change SSID or the key from the default you can use

      snap set nm-wifi-hotspot ssid="My Cool SSID"
      snap set nm-wifi-hotspot psk="abcdefghijk"

grade: stable
confinement: strict

apps:
  nm-wifi-hotspot:
    command: bin/launch
    stop-command: bin/wifi-hotspot wlan0 down
    daemon: oneshot
    install-mode: disable
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - network
      - network-bind
      - network-manager
      - process-control

parts:
  wifi-hotspot:
    source: https://github.com/NetworkManager/NetworkManager.git
    source-subdir: examples/python/dbus
    source-depth: 1
    plugin: dump
    override-pull: |
      snapcraftctl pull
      patch -p0 <$SNAPCRAFT_PROJECT_DIR/patches/wifi-hotspot.patch
    organize:
      wifi-hotspot.py: bin/wifi-hotspot
    prime:
      - -*.py
    stage-packages:
      - python3-dbus
  launcher:
    plugin: dump
    source: scripts
    organize:
      launcher.sh: bin/launch
